[package]
name = "parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
nom-indent = { git = "https://github.com/monomadic/nom-indent" }
nom_locate = "4.0.0"